Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 31/03/2023
Var
// Seção de Declarações das variáveis 
l:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para l de 101 ate 199 passo 2  faca

   escreva(l)
   fimpara

Fimalgoritmo